givery-bootcamp/dena-2024-team10

- docs/swagger.yaml
> swagger.yaml に getPosts の example を追加

- .github/workflows/frontend_test.yml
- frontend/package.json
> フロントエンドのCIを追加

- .github/workflows/backend_test.yml
- README.md
- backend/internal/config/config.go
- backend/internal/external/mysql.go
- docker-compose.yml
- docker/backend.Dockerfile
> refactor: add password for mysql

- .github/workflows/deploy.yml
- docker/frontend-ci.Dockerfile
- frontend/app/apiClient/apiClient.ts
> フロントのデプロイ追加

- docker/backend-ci.Dockerfile
> CI用のDockerファイルを追加

- docs/swagger.yaml
- インデントおかしかったから、リファクタ
- signup/in/out のAPI定義
- リクエストパラメータの定義
- 200系のレスポンス定義
- 400エラーの定義
- /posts にcookieパラメータが必要であることを明記
> signup/in/out のAPI定義

- .github/workflows/deploy.yml
> chore: change branch to only main

- docs/swagger.yaml
close #41
投稿系のAPI仕様を定義
swagger.yamlの追記
APIの実装
> 投稿系のAPI仕様書の追加

- backend/go.mod
- backend/internal/controllers/auth_controller.go
- backend/internal/controllers/schema/auth_request.go
- backend/internal/interfaces/user_repository.go
- backend/internal/middleware/router.go
- backend/internal/repositories/user_repository.go
- backend/internal/usecases/signup_usecase.go
- backend/test/mock/mock_interfaces/user_repository.go
- backend/test/repositories/user_repository_test.go
- backend/test/usecases/signup_usecase_test.go
> サインアップAPIの追加

- backend/internal/controllers/auth_controller.go
- backend/internal/middleware/router.go
- docs/swagger.yaml
#22 
サインアウトできない
- signout API を実装した
- Open API shema の更新
- cookie を消すだけなのでエラーハンドリングが発生しない
``` bash
% curl -X POST -c cookie.txt -d'{"username": "taro", "password": "password"}' localhost:9000/signin             
{"id":1,"username":"taro"}
% curl -bcookie.txt -XPOST -v localhost:9000/signout
* Host localhost:9000 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:9000...
* Connected to localhost (::1) port 9000
> POST /signout HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/8.6.0
> Accept: */*
> Cookie: Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTg2OTc0NTAsInVzZXJuYW1lIjoidGFybyJ9.0PsUjh-YxsON-jFPVWi7i27B-wJrH9LYc17ET9F4wEM
> 
< HTTP/1.1 204 No Content
< Content-Type: application/json; charset=utf-8
* Replaced cookie Authorization="" for domain localhost, …
```
> サインアウトAPIの実装

- backend/internal/controllers/hello_world_controller.go
- backend/internal/exception/exception.go
- backend/internal/middleware/error_handler.go
- backend/main.go
#39 
エラー処理が各々に任せられていたのでガバガバになっている
- エラーハンドリングを整備した
- `/hello` API に ↑ のエラーハンドリングを適用した
<details>
<summary>`/hello` の動作確認</summary>
200 を返す場合
400 を返す場合 (クエリパラメータのバリデーションに引っかかる)
404 を返す場合 (存在しないレコードを取得しようとしている)
500 を返す場合 (hello_world テーブルを削除した)
</details>
- [gin の middleware によるエラーハンドリング](https://qiita.com/safu9/items/b8c94bb911cb0a39d5aa)
- [Go言語におけるエラーハンドリングベストプラクティス](https://zenn.dev/malt03/articles/cd0365608a26c4)
スタックトレースをええ感じにやってくれるライブラリがあるっぽいが導入を断念した
golang.org/x/xerrors
> エラーハンドリングの導入

- .gitignore
- backend/internal/controllers/post_controller.go
- backend/internal/exception/exception.go
- backend/internal/interfaces/post_repository.go
- backend/internal/middleware/auth.go
- backend/internal/middleware/router.go
- backend/internal/repositories/post_repository.go
- backend/internal/usecases/delete_post_usecase.go
- backend/internal/usecases/signin_usecase.go
- backend/internal/utils/auth.go
- backend/test/mock/mock_interfaces/post_repository.go
- backend/test/repositories/post_repository_test.go
- backend/test/usecases/delete_post_usecase_test.go
- mysql/sql/drop.sql
#36 
- 投稿削除 API の実装
- 認証用の jwt に userID の追加
投稿が存在する際は正常に削除でき、削除済みの投稿に対しては NotFound が帰ってくることを確認した
``` bash
% curl -c cookie.txt -d'{"username":"taro", "password":"password"}' localhost:9000/signin
% curl -b cookie.txt localhost:9000/posts | jq .
[
{
"id": 1,
"title": "test1",
"body": "質問1\n改行",
"user_id": 1,
"username": "",
"created_at": "2024-06-25T12:29:31+09:00",
"updated_at": "2024-06-25T12:29:31+09:00"
},
{
"id": 2,
"title": "test2",
"body": "質問2\n改行",
"user_id": 1,
"username": "",
"created_at": "2024-06-25T12:29:31+09:00",
"updated_at": "2024-06-25T12:29:31+09:00"
}
]
% curl -b cookie.txt -X DELETE localhost:9000/posts/1
% curl -b cookie.txt localhost:9000/posts | jq .                                             
[
{
"id": 2,
"title": "test2",
"body": "質問2\n改行",
"user_id": 1, …
```
> Feature/#36 投稿削除 API の実装

- backend/internal/controllers/post_controller.go
- backend/internal/middleware/router.go
- backend/internal/usecases/get_post_usecase.go
- backend/test/usecases/get_post_usecase_test.go
close #3 
投稿詳細を取得するAPI
IDを指定して投稿を返す
> 投稿詳細APIの追加

- frontend/app/components/button.tsx
- frontend/app/components/dialog.tsx
- frontend/app/components/postForm.tsx
- frontend/app/routes/posts.$postId_.edit.tsx
- frontend/app/routes/posts.new.tsx
- Close #58 
issueに書いてあるとおり
- dialogのButtonをコンポーネントとして切り出し
- ついでにhoverで色変わるようにした
- PostFormにキャンセルボタンを実装
- 新規作成画面、編集画面にキャンセルボタンが実装される
**hoverで色変わるようにした**
https://github.com/givery-bootcamp/dena-2024-team10/assets/74412997/fa9b5936-2b6f-4125-a357-f5e95daf69c1
**編集画面にキャンセルボタン実装**
https://github.com/givery-bootcamp/dena-2024-team10/assets/74412997/673a9d45-715f-4931-8871-61499e7f81dc
**新規作成画面にキャンセルボタン実装**
https://github.com/givery-bootcamp/dena-2024-team10/assets/74412997/0256fc55-b6bf-4832-a45d-80dd9576efc8
> 新規作成画面と編集画面にキャンセルボタンを実装

- docs/swagger.yaml
下記APIの仕様を定義：
- コメント一覧
- 取得
- コメント詳細
- ~~取得~~
- 更新
- 削除
（全体的に Copilot に助けてもらいながら書いたので、抜け漏れあるかもしれませんmm）
> コメント機能のAPI仕様を追加

- docker-compose.yml
ポートを外部公開してしまっていた
ローカルに限定するように修正
> docker-composeで公開されるポートをローカルに限定

- backend/internal/controllers/auth_controller.go
close #69 
サインアップしてもサインインできなかった
サインアップ時は自動でサインインするようにした
> Signupが成功したら自動でSigninを行う

- backend/internal/controllers/post_controller.go
- backend/test/repositories/post_repository_test.go
- backend/test/usecases/get_all_post_usecase_test.go
なし
- GetAllPostsUsecase が nil を返す際には controller が空配列を返すようにした
``` bash
% curl -s -b cookie.txt 'localhost:9000/posts?offset=25'
[]
```
> fix: return empty list when results is nil

- frontend/app/root.tsx
- Close #56 
サインインしてない状態で一覧ページに飛ぶと、一覧取得APIを叩いたときに401が返ってくるので、エラーページが表示される
- /signin /signup 以外のPATHにサインインしてない状態(GET /user を叩いて判定)だったら、/signin にリダイレクトする
https://github.com/givery-bootcamp/dena-2024-team10/assets/74412997/26837c94-4b0a-4b25-bc5c-dcca845a8f58
処理をなぜこうしたか的なことをコードベースで書くんでぜひ読んでください
> サインインしていない状態でsignin/signup以外を叩くと、signinへリダイレクトされるよう実装

- backend/internal/controllers/post_controller.go
- backend/internal/controllers/schema/post_request.go
- backend/internal/exception/exception.go
- backend/internal/interfaces/post_repository_interface.go
- backend/internal/middleware/router.go
- backend/internal/repositories/post_repository.go
- backend/internal/usecases/create_post_usecase.go
- backend/internal/usecases/update_post_usecase.go
- backend/test/mock/mock_interfaces/post_repository_interface.go
- backend/test/repositories/post_repository_test.go
- backend/test/usecases/update_post_usecase_test.go
#37
投稿更新APIを実装した
```
curl -H "Content-Type: application/json" -X PUT -b cookie.txt -d '{"title":"テスト投稿更新やで", "body":"ふがふが〜！"}' http://localhost:9000/posts/1
{"id":0,"title":"テスト投稿更新やで","body":"ふがふが〜！","user_id":0,"username":"","created_at":"0001-01-01T00:00:00Z","updated_at":"2024-06-27T17:52:17.648+09:00"}%     
```
> Close #37 投稿更新APIを実装した

- frontend/app/routes/posts.$postId.tsx
> 自分の投稿ではない場合は編集ボタンを非表示

- backend/internal/middleware/router.go
投稿作成ができない
バックエンドの受け入れURLをpostからpostsにした
> rename /post to /posts

- frontend/app/routes/posts.$postId.comments.$commentId.tsx
close #95 
- delete commentのバグ修正
> bug-fix: コメント削除を叩くとこもfetchに変更

- frontend/app/routes/posts.$postId.tsx
無限ローディングの影響で、コメントを更新したときの挙動が不安定だった
無限ローディングをやめて、limitを固定値（100）に設定
> 無限ローティングをやめて、limitを100に設定
